label var individual_id "A number uniquely identifying all the records belonging to a specific individual in the data file."
label var hdss_name  "Name of HDSS site"
label var obs_date "Date of VA interview"
label var interviewer_id "ID number for the interviewer"

label var record_id "VA primary key"
label var age_group "Age group"

  
label var dob "Date of birth- best estimate"
label var dod "Date of death- best estimate"
label var sex "Male or female"
label var i004a "Did s(he) die during the wet season?"
label var i004b "Did s(he) die during the dry season?"
label var i019a "Was he male?"
label var i019b "Was she female?"
label var i022a "Was s(he) aged 65 years or more at death?"
label var i022b "Was s(he) aged 50 to 64 years at death?"
label var i022c "Was s(he) aged 15 to 49 years at death?"
label var i022d "Was s(he) aged 5-14 years at death?"
label var i022e "Was s(he) aged 1 to 4 years at death?"
label var i022f "Was s(he) aged 1 to 11 months at death?"
label var i022g "Was s(he) aged < 1 month (28 days) at death?"
label var i022h "Was s(he) a live baby who died within 24 hours of birth?"
label var i022i "Was s(he) a baby who died between 24 and 48 hours of birth?"
label var i022j "Was s(he) a baby who died more than 48 hours from birth, but within the first week?"
label var i022k "Was s(he) a baby who died after the first week, but"
label var i022l "Was she a woman aged 12-19 years at death?"
label var i022m "Was she a woman aged 20-34 years at death?"
label var i022n "Was she a woman aged 35 to 49 years at death?"
label var i059o "Was she married at the time of death?"
label var i077o "Did (s)he suffer from any injury or accident that led to her/his death?"
label var i079o "Was (s)he injured in a road traffic accident?"
label var i082o "Was (s)he injured in a non-road transport accident?"
label var i083o "Was (s)he injured in a fall?"
label var i084o "Was (s)he poisoned in any way?"
label var i085o "Did (s)he die of drowning?"
label var i086o "Was (s)he injured by the bite or sting of a venomous animal?"
label var i087o "Was (s)he injured by an animal or insect (non-venomous)"
label var i089o "Was (s)he injured by burns or fire?"
label var i090o "Was (s)he subject to violence (suicide, homicide,abuse)?"
label var i091o "Was (s)he injured by a fire arm?"
label var i092o "Was (s)he stabbed, cut or pierced?"
label var i093o "Was (s)he strangled?"
label var i094o "Was (s)he injured by a blunt force?"
label var i095o "Was (s)he injured by a force of nature?"
label var i096o "Was (s)he electrocuted?"
label var i098o "Was the injury accidental?"
label var i099o "Was the injury or accident self-inflicted?"
label var i100o "Was the injury or accident intentionally inflicted by someone else?"
label var i104o "Did the baby ever cry?"
label var i105o "Did the baby cry immediately after birth, even if only a little bit?"
label var i106a "Was it more than 5 minutes after birth before the baby first cried?"
label var i107o "Did the baby stop being able to cry?"
label var i108a "Did the baby stop crying more than a day before (s)he died?"
label var i109o "Did the baby ever move?"
label var i110o "Did the baby ever breathe?"
label var i111o "Did the baby breathe immediately after birth, even a little?"
label var i112o "Did the baby have a breathing problem?"
label var i113o "Was the baby given assistance to breathe at birth?"
label var i114o "If the baby didn't show any sign of life, was it born dead?"
label var i115o "Were there any bruises or signs of injury on child's body after the birth?"
label var i116o "Was the baby's body soft, pulpy and discoloured with the skin peeling away?"
label var i120a "Did the final illness last less than 3 weeks?"
label var i120b "Did the final illness last at least 3 weeks?"
label var i123o "Did (s)he die suddenly?"
label var i125o "Was there any diagnosis by a health professional of"
label var i127o "Was there any diagnosis by a health professional of HIV/AIDS?"
label var i128o "Did (s)he have a recent positive test by a health professional for malaria?"
label var i129o "Did (s)he have a recent negative test by a health"
label var i130o "Was there any diagnosis by a health professional of dengue fever?"
label var i131o "Was there any diagnosis by a health professional of measles?"
label var i132o "Was there any diagnosis by a health professional of high blood pressure?"
label var i133o "Was there any diagnosis by a health professional of heart disease?"
label var i134o "Was there any diagnosis by a health professional of diabetes?"
label var i135o "Was there any diagnosis by a health professional of asthma?"
label var i136o "Was there any diagnosis by a health professional of epilepsy?"
label var i137o "Was there any diagnosis by a health professional of cancer?"
label var i138o "Was there any diagnosis by a health professional of Chronic Obstructive Pulmonary Disease (COPD)?"
label var i139o "Was there any diagnosis by a physician or health worker of dementia?"
label var i140o "Was there any diagnosis by a health professional of depression?"
label var i141o "Was there any diagnosis by a health professional of stroke?"
label var i142o "Was there any diagnosis by a health professional of sickle cell disease?"
label var i143o "Was there any diagnosis by a health professional of kidney disease?"
label var i144o "Was there any diagnosis by a health professional of liver disease?"
label var i147o "During the illness that led to death, did (s)he have a fever?"
label var i148a "Did the fever last less than a week before death?"
label var i148b "Did the fever last at least one week, but less than 2 weeks before death?"
label var i148c "Did the fever last at least 2 weeks before death?"
label var i149o "Did the fever continue until death?"
label var i150a "Was the fever severe?"
label var i151a "Was the fever continuous?"
label var i152o "Did (s)he have night sweats?"
label var i153o "During the illness that led to death, did (s)he have a cough?"
label var i154a "Did the cough last less than 3 weeks before death?"
label var i154b "Did the cough last at least 3 weeks before death?"
label var i155o "Was the cough productive, with sputum?"
label var i156o "Was the cough very severe?"
label var i157o "Did (s)he cough up blood?"
label var i158o "Did (s)he make a whooping sound when coughing?"
label var i159o "During the illness that led to death, did (s)he have any difficulty breathing?"
label var i161a "Did the difficult breathing last for at least 3 days before death?"
label var i165a "Was the difficult breathing continuous during this period?"
label var i166o "Did (s)he have fast breathing?"
label var i167a "Did the fast breathing last for less than two weeks before death?"
label var i167b "Did the fast breathing last for at least 2 weeks before death?"
label var i168o "Did (s)he have breathlessness?"
label var i169a "Did the breathlessness last for less than 2 weeks before death?"
label var i169b "Did the breathlessness last for at least 2 weeks before death?"
label var i170o "Was (s)he unable to carry out daily routines due to breathlessness?"
label var i171o "Was (s)he breathless while lying flat?"
label var i172o "Did you see the lower chest wall/ribs being pulled in as the child breathed?"
label var i173a "Did his/her breathing sound like wheezing or grunting?"
label var i174o "During the illness that led to death, did (s)he have chest pain?"
label var i175o "Was the chest pain severe?"
label var i176a "Did (s)he experience chest pain at least 3 days before death?"
label var i178a "Did the chest pain last for at least 30 minutes?"
label var i181o "Did (s)he have diarrhoea?"
label var i182a  "Did (s)he have diarrhoea for less than 2 weeks before death?"
label var i182b  "Did (s)he have diarrhoea for at least 2 weeks but less than 4 weeks before death?"
label var i182c "Did (s)he have diarrhoea for at least 4 weeks before death?"
label var i183a "Did the baby or child have at least 4 stools on the day that loose liquid stools were most frequent?"
label var i184a "Did the frequent loose or liquid stools start at least 3 days before death?"
label var i185o "Did the frequent loose or liquid stools continue up until death?"
label var i186o "At any time during the final illness was there blood in the stools?"
label var i187o "Was there blood in the stool up until death?"
label var i188o "During the illness that led to death, did (s)he vomit?"
label var i189o "Did (s)he vomit in the week preceding the death?"
label var i190o "Did (s)he vomit for at least 3 days before death?"
label var i191o "Was there blood in the vomit?"
label var i192o "Was the vomit black?"
label var i193o "During the illness that led to death, did (s)he have any abdominal (belly) problem?"
label var i194o "Did (s)he have abdominal pain?"
label var i195o "Was the abdominal pain severe?"
label var i197a "Did (s)he have severe abdominal pain for less than 2 weeks before death?"
label var i197b "Did (s)he have severe abdominal pain for at least 2 weeks before death?"
label var i199a "Was the pain in the upper abdomen?"
label var i199b "Was the pain in the lower abdomen?"
label var i200o "Did (s)he have a more than usually protruding abdomen?"
label var i201a "Did (s)he have a more than usually protruding abdomen for less than 2 weeks before death?"
label var i201b "Did (s)he have a more than usually protruding abdomen for at least 2 weeks before death?"
label var i203a "Did (s)he develop the protruding abdomen rapidly?"
label var i204o "Did (s)he have any mass in the abdomen?"
label var i205a "Did (s)he have a mass in the abdomen for less than 2 weeks before death?"
label var i205b "Did (s)he have a mass in the abdomen for at least 2 weeks before death?"
label var i207o "During the illness that led to death, did (s)he have a severe headache?"
label var i208o "During the illness that led to death, did (s)he have a stiff neck?"
label var i209a "Did (s)he have a stiff neck for less than one week before death?"
label var i209b "Did (s)he have a stiff neck for at least one week before death?"
label var i210o "During the illness that led to death, did (s)he have a painful neck?"
label var i211a "Did (s)he have a painful neck for at least one week before death?"
label var i212o "During the illness that led to death, did (s)he have mental confusion?"
label var i213o "Did (s)he have mental confusion for at least 3 months before death?"
label var i214o "During the illness that led to death, was (s)he unconscious?"
label var i215o "Was (s)he unconscious for at least 24 hours before death?"
label var i216a "Was (s)he unsconscious for at least 6 hours before death?"
label var i217o "Did the unconsciousness start suddenly, quickly (at least within a single day)?"
label var i218o "Did the unconsciousness continue until death?"
label var i219o "During the illness that led to death, did (s)he have any convulsions?"
label var i220o "Did (s)he experience any generalized convulsions or fits?"
label var i221a "Did the convulsions last for less than 10 minutes?"
label var i221b "Did the convulsions last for at least 10 minutes?"
label var i222o "Did (s)he become unconscious immediately after the convulsion?"
label var i223o "During the illness that led to death, did (s)he have any urine problems?"
label var i224o "Did (s)he stop urinating?"
label var i225o "Did (s)he go to urinate more often than usual?"
label var i226o "Did (s)he pass blood in the urine?"
label var i227o "During the illness that led to death, did (s)he have any sores or ulcers anywhere?"
label var i228o "Did (s)he have sores?"
label var i229o "Did the sores have clear fluid and/or pus?"
label var i230o "Did (s)he have an ulcer (pit) on the foot?"
label var i231o "Did any ulcer ooze pus?"
label var i232a "Did the ulcer ooze pus for at least 2 weeks?"
label var i233o "During the illness that led to death, did (s)he have any skin rash?"
label var i234a "Did (s)he have the skin rash for less than one week?"
label var i234b "Did (s)he have the skin rash for at least one week?"
label var i235a "Did (s)he have a rash on the face?"
label var i235b "Did (s)he have a rash on the trunk or abdomen?"
label var i235c "Did (s)he have a rash on the extremities?"
label var i235d "Did (s)he have a rash everywhere?"
label var i236o "Did (s)he have measles rash?"
label var i237o "Did (s)he ever have shingles or herpes zoster?"
label var i238o "During the illness that led to death, did her/his skin flake off in patches?"
label var i239o "During the illness that led to death, did he/she have areas of the skin that turned black?"
label var i240o "During the illness that led to death, did he/she have areas of the skin with redness and swelling?"
label var i241o "During the illness that led to death, did (s)he bleed from anywhere?"
label var i242o "Did (s)he bleed from the nose, mouth or anus?"
label var i243o "During the illness that led to death, did (s)he have noticeable weight loss?"
label var i244o "Was (s)he severely thin or wasted?"
label var i245o "During the illness that led to death, did s/he have a whitish rash inside the mouth or on the tongue?"
label var i246o "During the illness that led to death, did (s)he have stiffness of the whole body or was unable to open the mouth?"
label var i247o "During the illness that led to death, did (s)he have puffiness of the face?"
label var i248a "Did (s)he have puffiness of the face for at least one week before death?"
label var i249o "During the illness that led to death, did (s)he have swollen legs or feet?"
label var i250a "Did the swelling last for at least 3 days before death?"
label var i251o "Did (s)he have both feet swollen?"
label var i252o "During the illness that led to death, did (s)he have general puffiness all over his/her body?"
label var i253o "During the illness that led to death, did (s)he have any lumps?"
label var i254o "Did (s)he have any lumps or lesions in the mouth?"
label var i255o "Did (s)he have any lumps in the neck?"
label var i256o "Did (s)he have any lumps in the armpit?"
label var i257o "Did (s)he have any lumps in the groin?"
label var i258o "During the illness that led to death, was (s)he in any way paralysed?"
label var i259o "Did (s)he have paralysis of only one side of the body?"
label var i260a "Was only the right side of the body paralysed?"
label var i260b "Was only the left side of the body paralysed?"
label var i260c "Was only the lower part of the body paralysed?"
label var i260d "Was only the upper part of the body paralysed?"
label var i260e "Was only one leg paralysed?"
label var i260f "Was only one arm paralysed?"
label var i260g "Was the entire body paralysed?"
label var i261o "During the illness that led to death, did (s)he have difficulty swallowing?"
label var i262a "Did (s)he have difficulty swallowing for at least one week before death?"
label var i263a "Did (s)he have difficulty with swallowing solids?"
label var i263b "Did (s)he have difficulty with swallowing liquids?"
label var i264o "Did (s)he have pain upon swallowing?"
label var i265o "During the illness that led to death, did (s)he have yellow discolouration of the eyes?"
label var i266a "Did (s)he have the yellow discolouration for at least 3 weeks before death?"
label var i267o "During the illness that led to death, did her/his hair change to a reddish or yellowish colour?"
label var i268o "During the illness that led to death, did (s)he look pale (thinning/lack of blood) or have pale palms, eyes or nail beds?"
label var i269o "During the illness that led to death, did (s)he have sunken eyes?"
label var i270o "During the illness that led to death, did (s)he drink a lot more water than usual?"
label var i271o "Was the baby able to suckle or bottle-feed within the first 24 hours after birth?"
label var i272o "Did the baby ever suckle in a normal way?"
label var i273o "Did the baby stop suckling?"
label var i274a "Did the baby stop suckling on the 2nd day of life or later?"
label var i275o "Did the baby have convulsions starting within the first 24 hours of life?"
label var i276o "Did the baby have convulsions starting more than 24 hours after birth?"
label var i277o "Did the baby's body become stiff, with the back arched backwards?"
label var i278o "During the illness that led to death, did the baby have a bulging or raised fontanelle?"
label var i279o "During the illness that led to death, did the baby have a sunken fontanelle?"
label var i281o "During the illness that led to death, did the baby become unresponsive or unconscious?"
label var i282o "Did the baby become unresponsive or unconscious soon after birth, within less than 24 hours?"
label var i283o "Did the baby become unresponsive or unconscious more than 24 hours after birth?"
label var i284o "During the illness that led to death, did the baby become cold to touch?"
label var i285a "Was the baby more than 3 days old when it started feeling cold to touch?"
label var i286o "During the illness that led to death, did the baby become lethargic, after a period of normal activity?"
label var i287o "Did the baby have redness or discharge from the umbilical cord stump?"
label var i288o "During the illness that led to death, did the baby have skin ulcer(s) or pits?"
label var i289o "During the illness that led to death, did the baby have yellow skin, palms (hand) or soles (foot)?"
label var i290o "Did the baby or infant appear to be healthy and then just die suddenly?"
label var i294o "During the illness that led to death, did she have any swelling or lump in the breast?"
label var i295o "During the illness that led to death, did she have any ulcers (pits) in the breast?"
label var i296o "Did she ever have a period or menstruate?"
label var i297o "During the illness that led to death, did she have excessive vaginal bleeding in between menstrual periods?"
label var i298o "Was the bleeding excessive?"
label var i299o "Did her menstrual period stop naturally because of menopause?"
label var i300o "Did she have vaginal bleeding after cessation of menstruation?"
label var i301o "Was there excessive vaginal bleeding in the week prior to death?"
label var i302o "At the time of death was her period overdue?"
label var i303a "Had her period been overdue for at least 4 weeks?"
label var i304o "Did she have a sharp pain in her abdomen shortly before death?"
label var i305o "Was she pregnant at the time of death?"
label var i306o "Did she die within 6 weeks of delivery, abortion or miscarriage?"
label var i309o "Was she, or had she been, pregnant for less than 6 months when she died?"
label var i310o "Please confirm: When she died, she was NEITHER pregnant NOR had recently been pregnant NOR had recently delivered when she died - is that right?"
label var i312o "Did she die during labour, but before delivery?"
label var i313o "Did she die after delivering a baby?"
label var i314o "Did she die within 24 hours after delivery?"
label var i315o "Did she die within 6 weeks of childbirth?"
label var i316o "Did she give birth to a live baby (within 6 weeks of her death)?"
label var i317o "Did she die during or after a multiple pregnancy?"
label var i318o "Was she breastfeeding the child in the days before death?"
label var i319a "Did she die during or after her first pregnancy?"
label var i319b "Did she have four or more pregnancies before this one?"
label var i320o "Had she had any previous Caesarean section?"
label var i321o "During pregnancy, did she suffer from high blood"
label var i322o "Did she have foul smelling vaginal discharge during"
label var i323o "During the last 3 months of pregnancy, did she suffer from convulsions?"
label var i324o "During the last 3 months of pregnancy did she suffer from blurred vision?"
label var i325o "Did she have excessive bleeding during pregnancy or shortly after delivery?"
label var i326o "Was there vaginal bleeding during the first 6 months of pregnancy?"
label var i327o "Was there vaginal bleeding during the last 3 months of pregnancy but before labour started?"
label var i328o "Did she have excessive bleeding during labour, before delivery?"
label var i329o "Did she have excessive bleeding after delivery or abortion?"
label var i330o "Was the placenta completely delivered?"
label var i331o "Did she deliver or try to deliver an abnormally positioned baby?"
label var i332a "Did her labour last longer than 24 hours?"
label var i333o "Did she attempt to terminate the pregnancy?"
label var i334o "Did she recently have a pregnancy that ended in an abortion (spontaneous or induced)?"
label var i335o "Did she die during an abortion?"
label var i336o "Did she die within 6 weeks of having an abortion?"
label var i337a "Did the mother deliver at a health facility or clinic?"
label var i337b "Did the mother deliver at home?"
label var i337c "Did the mother deliver elsewhere (not at a health facility nor at home)?"
label var i338o "Did she receive professional assistance during the delivery?"
label var i340o "Did she have an operation to remove her uterus shortly before death?"
label var i342o "Was the delivery normal vaginal, without forceps or vacuum?"
label var i343o "Was the delivery vaginal, with forceps or vacuum?"
label var i344o "Was the delivery a Caesarean section?"
label var i347o "Was her baby born more than one month early?"
label var i354o "Was the child part of a multiple  birth?"
label var i355a "If the child was part of a multiple birth, was it born first?"
label var i356o "Is the child's mother still alive?"
label var i357o "Did the child's mother die during or shortly after the delivery?"
label var i358a "Did the child's mother die in the baby's first year of life?"
label var i360a "Was the baby born in a health facility or clinic?"
label var i360b "Was the baby born at home?"
label var i360c "Was the baby born somewhere else (e.g. on the way to a clinic)?"
label var i361o "Did the mother receive professional assistance during the delivery?"
label var i362o "At birth, was the baby of usual size?"
label var i363o "At birth, was the baby smaller than normal (weighing under 2.5 kg)?"
label var i364o "At birth, was the baby very much smaller than usual, (weighing under 1 kg)?"
label var i365o "At birth, was the baby larger than normal (weighing over 4.5 kg)?"
label var i367a "Was the baby born during the ninth month (at least 37 weeks) of pregnancy?"
label var i367b "Was the baby born during the eighth month (34 to 37 weeks) of pregnancy?"
label var i367c "Was the baby born before the eighth month (less than 34 weeks) of pregnancy?"
label var i368o "Were there any complications in the late part of the pregnancy (defined as the last 3 months), but before labour?"
label var i369o "Were there any complications during labour or delivery?"
label var i370o "Was any part of the baby physically abnormal at time of delivery? (for example: body part too large or too small, additional growth on body)?"
label var i371o "Did the baby/child have a swelling or defect on the back?"
label var i372o "Did the baby/child have a very large head?"
label var i373o "Did the baby/child have a very small head?"
label var i376o "Was the baby moving in the last few days before the birth?"
label var i377o "Did the baby stop moving in the womb before labour started?"
label var i382a "Did labour and delivery take more than 24 hours?"
label var i383o "Was the baby born 24 hours or more after the waters broke?"
label var i384o "Was the liquor foul smelling when the waters broke?"
label var i385a "Was the liquor a green or brown colour when the waters broke?"
label var i387o "Was the delivery normal vaginal, without forceps or vacuum?"
label var i388o "Was the delivery vaginal, with forceps or vacuum?"
label var i389o "Was the delivery a Caesarean section?"
label var i391o "Did the child's mother receive any vaccinations since reaching adulthood including during this pregnancy?"
label var i393o "Did the mother receive tetanus toxoid (TT) vaccine?"
label var i394a "Was this baby born from the mother's first pregnancy?"
label var i394b "Did the baby's mother have four or more births before this one?"
label var i395o "During labour, did the baby's mother suffer from fever?"
label var i396o "During the last 3 months of pregnancy, labour or delivery, did the baby's mother suffer from high blood pressure?"
label var i397o "Did the baby's mother have diabetes mellitus?"
label var i398o "Did the baby's mother have foul smelling vaginal discharge during pregnancy or after delivery?"
label var i399o "During the last 3 months of pregnancy, labour or delivery, did the baby's mother suffer from convulsions?"
label var i400o "During the last 3 months of pregnancy did the baby's mother suffer from blurred vision?"
label var i401o "Did the baby's mother have severe anaemia?"
label var i402o "Did the baby's mother have vaginal bleeding during the last 3 months of pregnancy but before labour started?"
label var i403o "Did the baby's bottom, feet, arm or hand come out of the vagina before its head?"
label var i404o "Was the umbilical cord wrapped more than once around the baby's neck at birth?"
label var i405o "Was the umbilical cord delivered first?"
label var i406o "Was the baby blue in colour at birth?"
label var i408o "Before the illness that led to death, was the baby/child growing normally?"
label var i411o "Did (s)he drink alcohol?"
label var i412o "Did (s)he use tobacco?"
label var i413o "Did (s)he smoke tobacco (cigarette, cigar, pipe, etc.)?"
label var i414a "Did (s)he use non-smoking tobacco?"
label var i415a "Did (s)he smoke at least 10 cigarettes daily?"
label var i418o "Did (s)he receive any treatment for the illness that led to death?"
label var i419o "Did (s)he receive oral rehydration salts?"
label var i420o "Did (s)he receive (or need) intravenous fluids (drip) treatment?"
label var i421o "Did (s)he receive (or need) a blood transfusion?"
label var i422o "Did (s)he receive (or need) treatment/food through a tube passed through the nose?"
label var i423o "Did (s)he receive (or need) injectable antibiotics?"
label var i424o "Did (s)he receive (or need) antiretroviral therapy (ART)?"
label var i425o "Did (s)he have (or need) an operation for the illness?"
label var i426o "Did (s)he have the operation within 1 month before death?"
label var i427o "Was (s)he discharged from hospital very ill?"
label var i428o "Did (s)he receive appropriate immunizations?"
label var i450o "In the final days before death, did s/he travel to a hospital or health facility?"
label var i451o "Did (s)he use motorised transport to get to the hospital or health facility?"
label var i452o "Were there any problems during admission to the hospital or health facility?"
label var i453o "Were there any problems with the way (s)he was treated (medical treatment, procedures, interpersonal attitudes, respect, dignity) in the hospital or health facility?"
label var i454o "Were there any problems getting medications, or diagnostic tests in the hospital or health facility?"
label var i455o "Does it take more than 2 hours to get to the nearest hospital or health facility from the deceased's household?"
label var i456o "In the final days before death, were there any doubts about whether medical care was needed?"
label var i457o "In the final days before death, was traditional medicine used?"
label var i458o "In the final days before death, did anyone use a telephone or cell phone to call for help?"
label var i459o "Over the course of illness, did the total costs of care and treatment prohibit other household payments?"


